services:
  app:
    build: .
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=videodb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    container_name: mydb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=videodb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
